development:
  adapter: postgresql
  encoding: unicode
  database: jm_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: jm_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: jm_production
  pool: 5
  timeout: 5000
